### ISSUE TITLE
Update signaling list and  update  it's header

### ISSUE THREAD

**Issue by serapieTuyishime** [wavvapp/sac-frontend#40]
### **Objective:**
The goal is to update a Signaling list component with the new design. 

### **Description:**

- Update `Signaling.tsx` component  inside `components/list/` folder according to the new design.
- We no longer Display the number of friends in the badge component.
- We have  **Friends** tittle in the top left corner and **FIND** button in the top right corner.
- Use the updated ```User Availability card``` to indicated the user availability 
- When there's no friends who turned on their signal we must render the following text ```None of your friends on Wavv are available today``` with proper font in the upper part of the screen 
- The first upper part of the screen with white background represents the friends who are currently available 
- The second lower part of the screen with grey background renders the friends who are currently offline .
- Make the implementation match the new  Figma design
- The component is still rendered in  the Home screen

### **Acceptance Criteria:**
- The component still receives an array of objects containing user information
- The component matches the  update Figma design
### **Design:**
![Image](https://github.com/user-attachments/assets/363e8b5d-3282-49d7-b3cc-4cf617a87c21)

**Comment by AnasAlamin** [comment]
the card there is twitching and not at all very native (in looks and feel) we might need to do it from scratch. plus if we turn the signal off/on multiple times, sometimes the whole bottom sheet just disappears.

@darioaschero  what do you think?

**Comment by igorntwari** [comment]
> the card there is twitching and not at all very native (in looks and feel) we might need to do it from scratch. plus if we turn the signal off/on multiple times, sometimes the whole bottom sheet just disappears.
> 
> [@darioaschero](https://github.com/darioaschero) what do you think?

@AnasAlamin are you referring to this toggle ?
![Image](https://github.com/user-attachments/assets/d30e3daf-2dc1-4067-b3c3-59c25b9e9c00)

Because this card is all about ```Signalist.tsx``` component inside ```component/list```
