### ISSUE TITLE
Create user availability card

### ISSUE THREAD

**Issue by serapieTuyishime** [wavvapp/sac-frontend#45]
### **Objective:**
Create the user availability card.
### **Description:**
* Create the userAvailability card component in `/components/cards`
* This component should replace the user Info card component in `/components/UserInfo.tsx`
* Display the user's name, activity, and time as is in the Figma design
* There is a component already named `UserAvailability.tsx` located at `components/UserAvailabilit.tsx`, change it's name to `Activity.tsx` component since it's where the user actually changes their activity.

### **Acceptance Criteria:**
* created the userAvailability
* the component is styled according to the Figma design
* the component previously named userAvailability is now named `Availability`

### **Design**

current userAvailability card

![Image](https://github.com/user-attachments/assets/d17d426c-7097-4f90-849e-520992aacca4)

Previously known as user info card

![Image](https://github.com/user-attachments/assets/6e1aabb0-3da4-4cd4-8274-36e3c89daedc)

component Previously known as `UserAvailability` that is to change to `Activity.tsx`
 ![Image](https://github.com/user-attachments/assets/6242e2f7-2d71-433d-87c7-72327aa4bb74)

**Comment by Odile078** [comment]
Currently blocked. The implementation is waiting for the updated font configuration to have access to  `iA Writer Mono S` font-family
