### ISSUE TITLE
Update user status card

### ISSUE THREAD

**Issue by serapieTuyishime** [wavvapp/sac-frontend#48]
Blocked by #45 

### **Objective:**
Update the user status card
### **Description:**

* Update the userStatus card component `/components/cards/UserStatus.tsx`
* The component has a state to save whether the status is visible to any friends or not
* When the status is visible, it should show the visible friends, and when it's not,  show:`status in not visible to any...` according to the Figma design

### **Acceptance Criteria:**
* the component is updated with the styles according to the Figma styles

### **Design:**
[Links or screenshots of the design]

![Image](https://github.com/user-attachments/assets/d5c20e5e-df56-4cb4-ae63-56b44dc86fd1)

**Comment by AnasAlamin** [comment]
I have a PR that, edits the codes in this component. please consider the new code there
